### ISSUE TITLE
Boolean is Bool in Elm

### ISSUE THREAD

**Issue by note89** [jahewson/elm-graphql#12]
The generated **elm** calls `Bool` for `Boolean/boolean`

## hotfix for others 
`graphql-make.sh`
```
perl -pi -e 's/Boolean/Bool/g' Your/Output/Foo.elm
perl -pi -e 's/boolean/bool/g' Your/Output/Foo.elm
```

**Comment by jahewson** [comment]
Fixed in 2e1b9d6b4955eb7e003c252573a7cb08188e43d9, thanks!
