### ISSUE TITLE
Compilation error in generated decoders

### ISSUE THREAD

**Issue by carleryd** [jahewson/elm-graphql#14]
After the most recent commits the generated Decoders use normal types instead of Json.Decode types.
The code for decoding a float, inside of a generated Decoder, now looks like this:
```
`apply` (maybe ("latitude" := (Maybe Float)))
```
which gives me errors, previously it looked like this:
```
`apply` (maybe ("latitude" := float))
```
which worked fine.

I am using Elm 0.17.1

**Comment by jahewson** [comment]
Hi, sorry I messed up my final refactoring of this code. Working on it now...!

**Comment by jahewson** [comment]
Ok, 2234a433d44b4c7bdb412abb738f45b0077a8ea3 should fix this.
