### ISSUE TITLE
Request does not work in firefox

### ISSUE THREAD

**Issue by note89** [jahewson/elm-graphql#16]
`Http.get` does not send any Accept header and firefox defaults to 
```
"Accept: text/html"
```

which results in this error 
```
<!--
The request to this GraphQL server provided the header "Accept: text/html"
and as a result has been presented GraphiQL - an in-browser IDE for
exploring GraphQL.
If you wish to receive JSON, provide the header "Accept: application/json" or
add "&raw" to the end of the URL within a browser.
-->
```

**Comment by jahewson** [comment]
I can't reproduce this with Firefox 45.0.1, which sets the Accept header to `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`.

What's the exact Accept head your browser is sending? (From FF developer tools). What GraphQL server are you using?

**Comment by note89** [comment]
This repo reproduces the same problem
[https://github.com/carleryd/elm-hipster-stack](url)
on firefox 46. 
Im using [https://github.com/graphql-elixir/graphql](url)
```Accept	
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8```

In firefox not using firebug you can `Edit and Resend`
if i edit to `application/json` and resend i get the correct response

**Comment by jahewson** [comment]
Looks like phoenix and express and handling the accept headers differently. I'm going to set the Accept header in Elm to avoid this.

**Comment by jahewson** [comment]
Ok, 7c1d60217f10256b692a7841b385ee0f4fa65307 adds the header.
