### ISSUE TITLE
Having the graphql fieldname (type) does not generate (type')

### ISSUE THREAD

**Issue by proProbe** [jahewson/elm-graphql#17]
Hello! Noticed a bug. Having a field in graphql named `type` should generate `type'` in elm

**Comment by proProbe** [comment]
http://graphql.org/docs/api-reference-type-system/#graphqlinputobjecttype

**Comment by jahewson** [comment]
Are you using the latest code? This was added in c80a0f8d213a3aa39a55e2e85cda0968559c3d2e.

**Comment by jahewson** [comment]
Closing due to lack of response. Feel free to reopen if this is still a problem.

**Comment by proProbe** [comment]
this seems to work now! Im sorry for the lack of response. Did not notice it until now

**Comment by jahewson** [comment]
Great, no worries!
