### ISSUE TITLE
Mutation query needs POST

### ISSUE THREAD

**Issue by patrickdet** [jahewson/elm-graphql#18]
Hey, as far as I can tell mutations are implemented but `query` always does a `GET` when mutations are expected to be `POST`. Am I doing something wrong?

**Comment by jahewson** [comment]
You're right. Mutations are new so please do report any further issues. Fixed in 9bb8837bc9c017340182d7036997b1e13a400bc0.

**Comment by patrickdet** [comment]
oh wow already fixed! thank you @jahewson 👍
