### ISSUE TITLE
Collaborate on apollo-codegen

### ISSUE THREAD

**Issue by stubailo** [jahewson/elm-graphql#33]
Hi! @martijnwalraven and I have been working on some tools to generate typed GraphQL results here: https://github.com/apollostack/apollo-codegen (this powers https://github.com/apollostack/apollo-ios)

You can see what a swift plugin looks like here: https://github.com/apollostack/apollo-codegen/tree/master/src/swift

And there is some work on TypeScript/Flow: https://github.com/apollostack/apollo-codegen/pull/5

If there is a possibility to share work here that would be cool! Otherwise everyone is kind of starting from scratch.

**Comment by jahewson** [comment]
Hi Sashko! Looks great. The IR concept is really nice. I'm wondering if I could make use of that in elm-graphql - beyond that it looks like you guys have it figured out already.

One thing I do regret about elm-graphql is that I generate Elm code by concatenating strings - I should have generated AST nodes and pretty printed them at the end.

Most of the tricky code in elm-graphql is devoted to generating the typed JSON encoders and decoders that Elm requires, of course in TypeScript you get this for free. I'd been wanting a TypeScript codegen so I might well have some contributions to make - it'll be far simpler than Elm!

**Comment by stubailo** [comment]
The iOS code has typed encoders and decoders! I don't know why we decided to do string concatenation (I guess it was just the simplest way) but @martijnwalraven might have a better idea of the tradeoffs.

I was thinking perhaps we could consolidate some of the boilerplate work together, so let me know if you're interested in talking about that sometime.
