### ISSUE TITLE
filter out replies that are wrong.

### ISSUE THREAD

**Issue by note89** [jahewson/elm-graphql#37]
Hi we have this `edges nodes` query that gets back a lot of results. 
Issue has been that if one of the nodes have a error `elm-graphql` throws` an error and we get nothing out. 
What would be a good approach to get the 999 other fields that are correct if one is wrong.

**Comment by jahewson** [comment]
What do you mean by "one of the nodes have a error", what kind of error? What's wrong with the fields?
