### ISSUE TITLE
"not a leaf type: undefined" error

### ISSUE THREAD

**Issue by puruzio** [jahewson/elm-graphql#38]
Thanks for sharing this awesome library.

As I'm trying it, I am getting the above error when running
`elm-graphql --init http://localhost:4000/graphql`

```
query-to-decoder.js:242
    throw new Error('not a leaf type: ' + type.name);
```

The graphql query/schema is a simple user list
```
query queryUsers(){
 users {
              id,
              email
     }
}

```

What does this error mean and how can I fix it? 

Thanks.

**Comment by jahewson** [comment]
What exactly is your schema?

**Comment by puruzio** [comment]
I'm using Elixir implementation of the graphql server, and here is the schema definition.
Basically, it's just the 3 fields in the user table.

defmodule SeatSaver.Schema do
  use Absinthe.Schema
  import_types SeatSaver.Schema.Types
  query do
    field :users, list_of(:user) do
      resolve &SeatSaver.UserResolver.all/2
    end
 
  end
end
 
 
defmodule SeatSaver.Schema.Types do
  use Absinthe.Schema.Notation
  use Absinthe.Ecto, repo: SeatSaver.Repo
  object :user do
    field :id, :id
    field :username, :string
    field :email, :string
  End
 
End

**Comment by jahewson** [comment]
Does the following query result in the same error?

```graphql
query queryUsers(){
 users {
              email
     }
}
```

**Comment by jahewson** [comment]
I've seen this error message when there's a different version of graphql-js being used on the server vs. elm-graphql. That's probably it, but without more details who knows?

**Comment by jaredramirez** [comment]
Having a similar issue with my schema defined as: 
```
const PostType = new GraphQLObjectType({
  name: 'Post',
  fields: {
    id: {
      type: new GraphQLNonNull(GraphQLString),
      description: 'Identifier of the post.',
    },
    title: {
      type: GraphQLString,
      description: 'Title of the post.',
    },
    body: {
      type: GraphQLString,
      description: 'Body of the post.',
    },
    stars: {
      type: new GraphQLList(GraphQLString),
      description: 'List of users that have starred the post.',
    },
    author: {
      type: GraphQLString,
      description: 'Author who wrote the post.',
    },
  },
});

const query = new GraphQLObjectType({
  name: 'RootQueryField',
  fields: {
    posts: {
      type: new GraphQLList(PostType),
      description: 'Retrieve all posts',
      resolve: getPostsResolver,
    },
});
```

and a `Posts.graphql` file that looks like this:
```
query {
  posts {
    id
    title
    body
    stars
    author
  }
}
```
