### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by jahewson** [jahewson/elm-graphql#5]
[Relay](https://facebook.github.io/relay/) is Facebook's data fetching layer for GraphQL. They use the ID type for caching objects and we could take the same approach in Elm. It seems like the cache itself might not be type safe, so we may have to store JSON. This is something I'm going to think about once Elm 0.17 is released because it should contain a lot of relevant new stuff.

**Comment by gyzerok** [comment]
I've been doing GraphQL since it was released and should mention that caching is extremely tricky stuff here.

My advice would be not touch it until you have full GraphQL support with good and stable API. For most of the real world projects Relay-style caching doesn't matter really.

**Comment by jahewson** [comment]
That's ok, I like tricky stuff.

I'm curious as to why you think that caching doesn't matter for "real world" projects? Caching is one of the main reasons for Relay existing at all and other GraphQL clients such as Lokka are doing caching too. Seems pretty important to me. Please can you offer some evidence to support your claim?

**Comment by jahewson** [comment]
Closing as I think that caching would be best implemented as a separate layer above elm-graphql.
