### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by note89** [jahewson/elm-graphql#6]
Hi ! 
We are a couple of guys that want to build our webapp with Elm and graphQL. 
Wonder if you could give us some guidelines on how to contribute to your repo, 
What to do and where to look for a solution. 

We are all new to Elm and GraphQl/Relay but are very interested in helping out.

**Comment by jahewson** [comment]
That's great. Make sure to check out the [Helpful Links](https://github.com/jahewson/elm-graphql/wiki/Helpful-Links) and [How elm graphql works](https://github.com/jahewson/elm-graphql/wiki/How-elm-graphql-works).

As far as contributing goes, create feature branches and submit PRs. You're welcome to tackle any open issues. I'm working on Fragments at the moment, but that's it.
